### ISSUE TITLE
16 Character Max for Names

### ISSUE THREAD

**Issue by hiown** [aarontwf/BattleNight-Core#18]
I have a user that has a 17 character name and it floods me with this Error Message whenever he joins a game:

[SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'bn' in plugin BattleNight v1.1
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:821)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:781)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:764)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:113)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.IllegalArgumentException: Player list names can only be a maximum of 16 characters long
    at org.bukkit.craftbukkit.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:177)
    at me.limebyte.battlenight.core.BattleNight.addPlayer(BattleNight.java:999)
    at me.limebyte.battlenight.core.BattleNight.onCommand(BattleNight.java:358)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

**Comment by hiown** [comment]
Is there any way I can do a quick fix for this myself as it is extremely bothersome to me

**Comment by aarontwf** [comment]
Not at the moment, sorry.  I though I fixed this :(

**Comment by aarontwf** [comment]
Can you please try version 1.1.2 and inform me if its fixed?  Link: http://bit.ly/bnlatest

**Comment by hiown** [comment]
I get this error when it starts to run.

00:15:45 [SEVERE] Could not load 'plugins\BattleNight.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: me.l
imebyte.battlenight.core.old.BattleNight
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:150)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:305)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:230)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:207)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:183)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigur
ationManager.java:53)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:156)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: me.limebyte.battlenight.core.old.Ba
ttleNight
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:139)
        ... 8 more

**Comment by aarontwf** [comment]
Fixing today.
