### ISSUE TITLE
1.3.1-R0.1 Build #02269  - Error for PlayerInteractEvent, PlayerQuitEvent

### ISSUE THREAD

**Issue by XxCoolGamesxX** [aarontwf/BattleNight-Core#45]
```
[SEVERE] Could not pass event PlayerInteractEvent to BattleNight
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177)
    at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:114)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:543)
    at net.minecraft.server.Packet14BlockDig.handle(SourceFile:46)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:281)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:105)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:559)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at me.limebyte.battlenight.core.BattleNight.tellEveryone(BattleNight.java:824)
    at me.limebyte.battlenight.core.Listeners.ReadyListener.onPlayerInteract(ReadyListener.java:47)
    at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
    ... 16 more
```

and

```
 [SEVERE] Could not pass event PlayerQuitEvent to BattleNight
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.ServerConfigurationManagerAbstract.disconnect(ServerConfigurationManagerAbstract.java:213)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:708)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:286)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:105)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:559)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at me.limebyte.battlenight.core.BattleNight.tellEveryoneExcept(BattleNight.java:860)
    at me.limebyte.battlenight.core.BattleNight.removePlayer(BattleNight.java:1123)
    at me.limebyte.battlenight.core.Listeners.DisconnectListener.onPlayerQuit(DisconnectListener.java:25)
    at sun.reflect.GeneratedMethodAccessor357.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
    ... 14 more
```

**Comment by aarontwf** [comment]
Hmm, looks like something is blocking BattleNight from sending messages to players on your server.

**Comment by XxCoolGamesxX** [comment]
I have the error.  I update to 1.3.1 - 2269 Build. It work in the old 1.2.5 - R5.0

**Comment by aarontwf** [comment]
It will be a bug in Bukkit then or a change Bukkit has made.  I will not be updating BattleNight until a RB is out so until then either go back to 1.2.5 or wait until the RB comes out.  However if it is a CraftBukkit bug I will most likely be resolved so keep CraftBukkit updated.

**Comment by XxCoolGamesxX** [comment]
Now bukkit have a Recommended Build of 1.3.1-R1.0 Build 2317

**Comment by aarontwf** [comment]
Can you confirm this issue still occurs with the RB?

**Comment by XxCoolGamesxX** [comment]
Yes. Work ok now in 1.3.1-R1.1 - 2325 Build

**Comment by XxCoolGamesxX** [comment]
Sorry my bad. I it not test 100%. Now I test it. I have the error of the PlayerQuitEvent and PlayerInteractEvent.

**Comment by aarontwf** [comment]
Ok, try this version and let me know if it fixed it: http://bit.ly/bnlatestdev
