### ISSUE TITLE
Error when exiting player

### ISSUE THREAD

**Issue by cbprog** [aarontwf/BattleNight-Core#48]
When one player is in the bluelounge area and writes /bn leave, the server displays a message indicating - You have left the Battle. However, the player is left in place, it is not teleported to the exit area. In addition, the player will lose all the items.
Player in bluelounge which chose battle class (tank or others) can use /spawn with battle items.
If 2 or more players - all fine.
If you type / bn kickall, player teleported. But this command is not available for players.
Server CraftBukkit-1.3.1-R2.0
Battlenight - last.
Tried to reinstall, did not help.
Sorry for my English )

**Comment by Arcental** [comment]
I have the same problem too. When a player exits the arena (/bn exit) after choosing a class, the items that they get for the classes doesn't get removed from the player.

**Comment by aarontwf** [comment]
Try this and let me know if it is fixed: http://bit.ly/bnlatestdev

**Comment by Arcental** [comment]
I think its working again :D TY!

Edit : If they disconnect while choosing a class then they are still in the lobby.

**Comment by aarontwf** [comment]
Ok

**Comment by cbprog** [comment]
Good fix.I again opened the arena for the players.
But after the battle, the winner teleported to the hall, and the loser is still in place (arena area).

``` Java
2012-09-18 16:44:39 [SEVERE] Could not pass event PlayerDeathEvent to BattleNight
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:322)
    at net.minecraft.server.EntityPlayer.die(EntityPlayer.java:307)
    at net.minecraft.server.EntityLiving.damageEntity(EntityLiving.java:663)
    at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
    at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:349)
    at net.minecraft.server.EntityArrow.h_(EntityArrow.java:222)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1239)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:498)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1221)
    at net.minecraft.server.World.tickEntities(World.java:1119)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:565)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at me.limebyte.battlenight.core.BattleNight.resetBattle(BattleNight.java:1141)
    at me.limebyte.battlenight.core.BattleNight.removePlayer(BattleNight.java:1116)
    at me.limebyte.battlenight.core.Listeners.DeathListener.onEntityDeath(DeathListener.java:71)
    at sun.reflect.GeneratedMethodAccessor241.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
    ... 18 more
```

**Comment by aarontwf** [comment]
Thanks!  Now I know where to look.

**Comment by aarontwf** [comment]
Ok, try this: http://bit.ly/bnlatestdev

**Comment by Arcental** [comment]
If you disconnect while in the lobby (Picking classes) you will be in the lobby still after relogin

edit : You also don't get teleported after win/losing/dieing in the match

**Comment by cbprog** [comment]
ok...go next :)

``` Java
2012-09-19 14:48:38 [SEVERE] Could not pass event PlayerDeathEvent to BattleNight
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:322)
    at net.minecraft.server.EntityPlayer.die(EntityPlayer.java:307)
    at net.minecraft.server.EntityLiving.damageEntity(EntityLiving.java:663)
    at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
    at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:349)
    at net.minecraft.server.EntityArrow.h_(EntityArrow.java:222)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1239)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:498)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1221)
    at net.minecraft.server.World.tickEntities(World.java:1119)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:565)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at me.limebyte.battlenight.core.BattleNight.resetBattle(BattleNight.java:1141)
    at me.limebyte.battlenight.core.BattleNight.removePlayer(BattleNight.java:1116)
    at me.limebyte.battlenight.core.Listeners.DeathListener.onEntityDeath(DeathListener.java:71)
    at sun.reflect.GeneratedMethodAccessor234.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
    ... 18 more
```

and

``` Java
2012-09-19 15:04:53 [SEVERE] Could not pass event PlayerDeathEvent to BattleNight
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:332)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:322)
    at net.minecraft.server.EntityPlayer.die(EntityPlayer.java:307)
    at net.minecraft.server.EntityLiving.damageEntity(EntityLiving.java:663)
    at net.minecraft.server.EntityHuman.damageEntity(EntityHuman.java:595)
    at net.minecraft.server.EntityPlayer.damageEntity(EntityPlayer.java:349)
    at net.minecraft.server.EntityHuman.attack(EntityHuman.java:762)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1020)
    at net.minecraft.server.Packet7UseEntity.handle(SourceFile:36)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:581)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.util.NoSuchElementException
    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.HashMap$EntryIterator.next(Unknown Source)
    at java.util.HashMap$EntryIterator.next(Unknown Source)
    at me.limebyte.battlenight.core.BattleNight.resetPlayer(BattleNight.java:1175)
    at me.limebyte.battlenight.core.BattleNight.resetBattle(BattleNight.java:1146)
    at me.limebyte.battlenight.core.BattleNight.removePlayer(BattleNight.java:1118)
    at me.limebyte.battlenight.core.Listeners.DeathListener.onEntityDeath(DeathListener.java:71)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:330)
    ... 20 more
```

**Comment by cbprog** [comment]
Man, if you have no place to test your plugin, you can do it on my server. Russian server, but I can help detect the errors for you. If anything, you can contact with me.
server 24/7.
p.s. Really nice plugin, and so bad that it has errors.

**Comment by aarontwf** [comment]
Servers is not an issue, time is at the moment.  Will try fix if I have some free time this weekend.

**Comment by Arcental** [comment]
I hope it gets fix in the next fix :)

**Comment by aarontwf** [comment]
Ok, I have just finished [the new dev version](http://bit.ly/bnlatestdev) which should have fixed a whole lot of bugs.

If do however find any bugs in this version please post them here.

**Comment by Arcental** [comment]
I was testing the plugin on my friends faction server and so it looks like BattleNight is completely working. Thanks for the fix LimeByte. If I find anymore bugs I'll be sure to inform you about it.

**Comment by cbprog** [comment]
Hi. Thank you, everything is fine with teleportation 0 errors.
I'm with a new request. You know that if you choose a class Tank or the other, on the label appears your name.
But there is one problem. If a player at random out of the game (disconnect), the player name on the label remains.
1) You can make the character's name was not written on the label?
2) You can make the player did not press for the second time on a label, to select another class?

**Comment by aarontwf** [comment]
Can you please post these in separate issues.  Thanks.
