### ISSUE TITLE
 Unhandled exception executing command 'bn' in plugin BattleNight v1.0

### ISSUE THREAD

**Issue by ScottSpittle** [aarontwf/BattleNight-Core#7]
08:16:21 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'bn' in plugin BattleNight v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:461)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:818)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:778)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:761)
        at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:117)
        at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:33)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:229)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:112)
        at lishid.orebfuscator.hook.NetServerHandlerProxy.a(NetServerHandlerProxy.java:60)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:78)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:554)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:356)
        at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:167)
        at me.limebyte.battlenight.core.BattleNight.goToWaypoint(BattleNight.java:869)
        at me.limebyte.battlenight.core.BattleNight.onCommand(BattleNight.java:378)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
        ... 14 more

**Comment by aarontwf** [comment]
Was this a once off or is it constantly happening?

**Comment by ScottSpittle** [comment]
Yes it was a One Off.

**Comment by aarontwf** [comment]
Ok, I wouldn't worry about it unless it was more frequent.
