### ISSUE TITLE
/bn join Internal Error

### ISSUE THREAD

**Issue by ghost** [aarontwf/BattleNight-Core#96]
So I set 3 spawn points, the lobby and the exit, made all the class signs in the lobby (except pyro) and when i typed /bn join it said something along the lines of "internal error". This is what the console read:

```
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188)
at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchCommand(CraftServer.java:523)
at net.minecraft.server.v1_5_R2.PlayerConnection.handleCommand(PlayerConnection.java:966)
at net.minecraft.server.v1_5_R2.PlayerConnection.chat(PlayerConnection.java:884)
at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:841)
at net.minecraft.server.v1_5_R2.Packet3Chat.handle(Packet3Chat.java:44)
at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:578)
at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:474)
at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:407)
at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
```

Caused by: java.lang.NoClassDefFoundError: org/kitteh/tag/TagAPI
    at me.limebyte.battlenight.core.hooks.Nameplates.refresh(Nameplates.java:75)
    at me.limebyte.battlenight.api.util.PlayerData.reset(PlayerData.java:222)
    at me.limebyte.battlenight.api.battle.Battle.addPlayer(Battle.java:166)
    at me.limebyte.battlenight.api.battle.TeamedBattle.addPlayer(TeamedBattle.java:89)
    at me.limebyte.battlenight.core.commands.JoinCommand.onPerformed(JoinCommand.java:27)
    at me.limebyte.battlenight.api.util.BattleNightCommand.perform(BattleNightCommand.java:60)
    at me.limebyte.battlenight.core.commands.CommandManager.onCommand(CommandManager.java:47)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more

Can anyone help? I don't exactly know how to decipher these kind of things, sorry if i sound stupid.
Also I'm new here, I dont know why the odd text box appeared in the middle of the error log.

**Comment by aarontwf** [comment]
Update TagAPI http://dev.bukkit.org/server-mods/tag/
